// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"authentication/application"
	"authentication/infrastructure"
	"authentication/userinterface"
)

// Injectors from wire.go:

func InitializeAuthController() *userinterface.AuthController {
	authRepository := infrastructure.NewAuthRepository()
	db := infrastructure.GetDB()
	authService := application.NewAuthService(authRepository, db)
	authController := userinterface.NewAuthController(authService)
	return authController
}
