services:
  nowdb:
    container_name: nowdb
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nowdb
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  nowapi:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nowdb

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./swagge/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
