services:
  nowdb:
    container_name: nowdb
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nowdb
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  migration:
    container_name: migration
    build:
      context: ./migration
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - nowdb
    volumes:
      - ./migration:/src
    command: ["tail", "-f", "/dev/null"]

  nowapi:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nowdb
      - nats-streaming
    volumes:
      - ./:/app:delegated

  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./stan:/data
    command: "-m 8222 --store file --dir /data/stan"
