definitions:
  userinterface.UserRequest:
    properties:
      id:
        type: integer
    type: object
  userinterface.UserResponse:
    properties:
      date_of_birth:
        type: integer
      email:
        type: string
      gender:
        type: string
      height:
        type: integer
      id:
        type: integer
      occupation:
        type: string
      residence:
        type: string
      status:
        type: integer
      user_name:
        type: string
      weight:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    get:
      description: 指定ユーザーのプロフィール確認時呼ばれる API
      parameters:
      - description: ID
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userinterface.UserResponse'
      summary: ユーザープロフィール情報参照 API
swagger: "2.0"
