definitions:
  userinterface.ApprovalRequest:
    properties:
      liked_user_id:
        type: integer
      user_id:
        type: integer
    type: object
  userinterface.GetLikeRequest:
    properties:
      user_id:
        type: integer
    type: object
  userinterface.GetLikedResponse:
    properties:
      liked_date:
        type: string
      liked_user_id:
        type: integer
      message_body:
        type: string
    type: object
  userinterface.LikeRequest:
    properties:
      liked_user_id:
        type: integer
      message_body:
        type: string
      user_id:
        type: integer
    type: object
  userinterface.UserDetailResponse:
    properties:
      date_of_birth:
        type: integer
      gender:
        type: string
      height:
        type: integer
      occupation:
        type: string
      residence:
        type: string
      user_id:
        type: integer
      weight:
        type: integer
    type: object
  userinterface.UserRequest:
    properties:
      id:
        type: integer
    type: object
  userinterface.UserResponse:
    properties:
      date_of_birth:
        type: integer
      email:
        type: string
      gender:
        type: string
      height:
        type: integer
      id:
        type: integer
      occupation:
        type: string
      residence:
        type: string
      status:
        type: integer
      user_name:
        type: string
      weight:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/like:
    get:
      description: 自身にいいねをしたユーザー一覧を表示した時呼ばれる API
      parameters:
      - description: UserID
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.GetLikeRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/userinterface.GetLikedResponse'
            type: array
      summary: いいね一覧参照 API
    post:
      description: ユーザーがいいねした時呼ばれる API
      parameters:
      - description: UserID, LikedUserID, MessageBody
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.LikeRequest'
      responses:
        "200":
          description: OK
      summary: いいね API
  /api/v1/like/approval:
    post:
      description: ユーザーがいいね一覧からユーザーを選び承認時呼ばれる API
      parameters:
      - description: UserID, LikedUserID
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.ApprovalRequest'
      responses:
        "200":
          description: OK
      summary: ユーザー承認 API
  /api/v1/users:
    get:
      description: 指定ユーザーのプロフィール確認時呼ばれる API
      parameters:
      - description: ID
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userinterface.UserResponse'
      summary: ユーザープロフィール情報参照 API
    put:
      description: 自身のプロフィール情報更新時呼ばれる API
      parameters:
      - description: ID, DateOfBirth, Gender, Residence, Occupation, Height, Weight
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/userinterface.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userinterface.UserDetailResponse'
      summary: ユーザープロフィール情報更新 API
swagger: "2.0"
