name: Run Swag Generater
on:
  workflow_dispatch:
  push:
    paths:
      - "pkg/userinterface/**.go"

jobs:
  swag:
    permissions:
      actions: write
      checks: write
      contents: write
    name: Run Swag and commit changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.3"
      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Run Swag
        run: swag init
      - name: Generate Html
        run: |
          npm install -g bootprint
          npm install -g bootprint-openapi
          cd ./docs
          bootprint openapi swagger.json .
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update swagger
