name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'

      - name: checkout
      - uses: actions/checkout@v3

      - name: golangci-lint
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"

      - name: testing
      - run: go test ./... -coverprofile=coverage.out

      - name: report coverage
      - uses: k1LoW/octocov-action@v0
