name: Test
on:
  push:
      branches:
        - main
  pull_request:
jobs:
  golang-test:
    steps:
      - name: setup
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: testing
        run: go test ./... -coverprofile=coverage.out --１
      - name: create report
        uses: k1LoW/octocov-action@v0 --２
