name: Test
on:
  push:
      branches:
        - main
  pull_request:
jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20'
    - uses: actions/checkout@v4

    - uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        golangci_lint_flags: "--config=./.golangci.yml ./..."
        fail_on_error: true
        reporter: "github-pr-review"

    - run: go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0
